export const dummyProducts = [
  {
    _id: 'p001',
    name: 'Premium Liquid Detergent 5L',
    description: 'Heavy-duty liquid detergent for commercial and home laundry. Suitable for all fabric types, removes tough stains in one wash.',
    category: 'laundry',
    subCategory: 'Laundry Supplies',
    price: 4500,
    bestseller: true,
    image: ['https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=400&h=400&fit=crop&q=80'],
  },
  {
    _id: 'p002',
    name: 'Powdered Washing Soap 10kg',
    description: 'Industrial-grade powdered soap ideal for bulk laundry. Works in both cold and hot water.',
    category: 'laundry',
    subCategory: 'Laundry Supplies',
    price: 7800,
    bestseller: false,
    image: ['https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&h=400&fit=crop&q=80'],
  },
  {
    _id: 'p003',
    name: 'Fabric Softener & Conditioner 3L',
    description: 'Premium fabric conditioner that leaves clothes fresh and soft. Long-lasting fragrance.',
    category: 'laundry',
    subCategory: 'Laundry Supplies',
    price: 3200,
    bestseller: true,
    image: ['https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=400&fit=crop&q=80'],
  },
  {
    _id: 'p004',
    name: 'Heavy-Duty Floor Cleaner 5L',
    description: 'Concentrated floor cleaner for tiles, marble, and concrete. Leaves surfaces streak-free and sanitized.',
    category: 'cleaning',
    subCategory: 'Cleaning Agents',
    price: 3900,
    bestseller: false,
    image: ['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&q=80'],
  },
  {
    _id: 'p005',
    name: 'Multi-Surface Disinfectant Spray',
    description: 'Kills 99.9% of germs on kitchen counters, bathrooms, and office surfaces. Ready-to-use formula.',
    category: 'cleaning',
    subCategory: 'Cleaning Agents',
    price: 1800,
    bestseller: true,
    image: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop&q=80'],
  },
  {
    _id: 'p006',
    name: 'Toilet Bowl Cleaner 1L',
    description: 'Thick gel formula clings to toilet bowl surfaces and eliminates stains, limescale and odors.',
    category: 'cleaning',
    subCategory: 'Cleaning Agents',
    price: 950,
    bestseller: false,
    image: ['https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&h=400&fit=crop&q=80'],
  },
  {
    _id: 'p007',
    name: 'Glass & Surface Cleaner 500ml',
    description: 'Streak-free formula for windows, mirrors, and glass surfaces. Dries instantly.',
    category: 'cleaning',
    subCategory: 'Cleaning Agents',
    price: 1200,
    bestseller: false,
    image: ['https://images.unsplash.com/photo-1527515637462-cff94aca0875?w=400&h=400&fit=crop&q=80'],
  },
  {
    _id: 'p008',
    name: 'Industrial Vacuum Cleaner',
    description: 'Heavy-duty wet and dry vacuum cleaner with 20L capacity. Ideal for post-construction and commercial cleaning.',
    category: 'machines',
    subCategory: 'Tools & Equipment',
    price: 85000,
    bestseller: true,
    image: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&q=80'],
  },
  {
    _id: 'p009',
    name: 'Microfibre Mop & Bucket Set',
    description: 'Commercial-grade mop with spin bucket, self-wringing mechanism, and two microfibre mop heads.',
    category: 'machines',
    subCategory: 'Tools & Equipment',
    price: 12500,
    bestseller: false,
    image: ['https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&h=400&fit=crop&q=80'],
  },
  {
    _id: 'p010',
    name: 'Pressure Sprayer 5L',
    description: 'Manual pump sprayer for pesticides, disinfectants, and liquid fertilisers. Adjustable nozzle.',
    category: 'machines',
    subCategory: 'Tools & Equipment',
    price: 6400,
    bestseller: false,
    image: ['https://images.unsplash.com/photo-1603807008857-ad66b70431aa?w=400&h=400&fit=crop&q=80'],
  },
  {
    _id: 'p011',
    name: 'Whitener & Bleach 2L',
    description: 'Concentrated chlorine bleach for laundry whitening, surface disinfection and mould removal.',
    category: 'laundry',
    subCategory: 'Laundry Supplies',
    price: 1450,
    bestseller: false,
    image: ['https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=400&h=400&fit=crop&q=80'],
  },
  {
    _id: 'p012',
    name: 'Microfibre Cleaning Cloths (10 Pack)',
    description: 'Ultra-absorbent lint-free cloths for glass, surfaces and kitchen. Machine washable up to 500 times.',
    category: 'cleaning',
    subCategory: 'Tools & Equipment',
    price: 2800,
    bestseller: true,
    image: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&q=80'],
  },
];

export const dummyOrders = [
  {
    _id: 'o001',
    items: [
      { name: 'Premium Liquid Detergent 5L', amount: 2 },
      { name: 'Fabric Softener & Conditioner 3L', amount: 1 },
    ],
    address: {
      firstName: 'Adebayo',
      lastName: 'Okonkwo',
      street: '14 Awolowo Road, GRA',
      city: 'Ibadan',
      state: 'Oyo State',
      country: 'Nigeria',
      phone: '+234 801 234 5678',
    },
    amount: 12200,
    paymentMethod: 'Paystack',
    payment: true,
    status: 'Delivered',
    date: Date.now() - 8 * 24 * 60 * 60 * 1000,
  },
  {
    _id: 'o002',
    items: [
      { name: 'Industrial Vacuum Cleaner', amount: 1 },
    ],
    address: {
      firstName: 'Chioma',
      lastName: 'Nwosu',
      street: 'Plot 7 Trans-Amadi Layout',
      city: 'Port Harcourt',
      state: 'Rivers State',
      country: 'Nigeria',
      phone: '+234 802 987 6543',
    },
    amount: 85000,
    paymentMethod: 'Bank Transfer',
    payment: true,
    status: 'Shipped',
    date: Date.now() - 3 * 24 * 60 * 60 * 1000,
  },
  {
    _id: 'o003',
    items: [
      { name: 'Heavy-Duty Floor Cleaner 5L', amount: 3 },
      { name: 'Multi-Surface Disinfectant Spray', amount: 5 },
      { name: 'Toilet Bowl Cleaner 1L', amount: 4 },
    ],
    address: {
      firstName: 'Emeka',
      lastName: 'Eze',
      street: '22 Allen Avenue, Ikeja',
      city: 'Lagos',
      state: 'Lagos State',
      country: 'Nigeria',
      phone: '+234 703 456 7890',
    },
    amount: 24500,
    paymentMethod: 'Cash on Delivery',
    payment: false,
    status: 'Packing',
    date: Date.now() - 1 * 24 * 60 * 60 * 1000,
  },
  {
    _id: 'o004',
    items: [
      { name: 'Microfibre Mop & Bucket Set', amount: 2 },
      { name: 'Pressure Sprayer 5L', amount: 1 },
    ],
    address: {
      firstName: 'Fatima',
      lastName: 'Abdullahi',
      street: 'No 3 Sokoto Road, Wuse 2',
      city: 'Abuja',
      state: 'FCT',
      country: 'Nigeria',
      phone: '+234 815 321 0987',
    },
    amount: 31500,
    paymentMethod: 'Paystack',
    payment: true,
    status: 'Out for delivery',
    date: Date.now() - 12 * 60 * 60 * 1000,
  },
  {
    _id: 'o005',
    items: [
      { name: 'Powdered Washing Soap 10kg', amount: 5 },
      { name: 'Whitener & Bleach 2L', amount: 3 },
    ],
    address: {
      firstName: 'Yusuf',
      lastName: 'Bello',
      street: 'Block C, Ahmadu Bello Way',
      city: 'Kaduna',
      state: 'Kaduna State',
      country: 'Nigeria',
      phone: '+234 706 543 2109',
    },
    amount: 43350,
    paymentMethod: 'Cash on Delivery',
    payment: false,
    status: 'Order Placed',
    date: Date.now() - 2 * 60 * 60 * 1000,
  },
  {
    _id: 'o006',
    items: [
      { name: 'Glass & Surface Cleaner 500ml', amount: 6 },
      { name: 'Microfibre Cleaning Cloths (10 Pack)', amount: 2 },
    ],
    address: {
      firstName: 'Ngozi',
      lastName: 'Okeke',
      street: '5 Independence Layout',
      city: 'Enugu',
      state: 'Enugu State',
      country: 'Nigeria',
      phone: '+234 812 765 4321',
    },
    amount: 12800,
    paymentMethod: 'Paystack',
    payment: true,
    status: 'Delivered',
    date: Date.now() - 14 * 24 * 60 * 60 * 1000,
  },
];
